apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: dev
  labels:
    app: cerebro
    tier: app
spec:
  type: NodePort  
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30010
  selector:
    app: cerebro
    tier: app