apiVersion: v1
kind: Pod
metadata:
  name: db
  namespace: test
  labels:
    app: cerebro
    tier: db
spec:
  containers:
    - name: postgres
      image: joellots/cerebro:db
      env:
        - name: POSTGRES_DB
          value: "cerebro_db"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD
      ports:
        - containerPort: 5432